#!/bin/bash
# ================================================
#  Sports Terminal — Fully Automated VPS Setup
#  One command. Zero manual steps.
#  Run via hosting web console:
#    curl -fsSL https://git.io/sportsterminal-setup | bash
# ================================================
set -e

# ── Colors ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}   $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ── Config ──
REPO_URL="https://github.com/brendadeeznuts1111/sportsterminal.git"
INSTALL_DIR="/opt/sportsterminal"
DOMAIN="terminal.factory-wager.com"

echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  Sports Terminal — Auto Setup${NC}"
echo -e "${CYAN}  Domain: ${DOMAIN}${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# ═══════════════════════════════════════════════════
# 1. SYSTEM PREREQUISITES
# ═══════════════════════════════════════════════════
info "[1/8] Installing system prerequisites..."
apt-get update -qq >/dev/null 2>&1
apt-get install -y -qq curl git unzip >/dev/null 2>&1
ok "System packages ready"

# ═══════════════════════════════════════════════════
# 2. DOCKER
# ═══════════════════════════════════════════════════
info "[2/8] Installing Docker..."
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh >/dev/null 2>&1
  systemctl enable docker >/dev/null 2>&1
  systemctl start docker >/dev/null 2>&1
fi
if ! docker compose version &>/dev/null; then
  apt-get install -y -qq docker-compose-plugin >/dev/null 2>&1
fi
ok "Docker $(docker --version | cut -d' ' -f3 | tr -d ',') ready"

# ═══════════════════════════════════════════════════
# 3. BUN (for local scripts)
# ═══════════════════════════════════════════════════
info "[3/8] Installing Bun..."
if ! command -v bun &>/dev/null; then
  echo "" | curl -fsSL https://bun.sh/install | bash >/dev/null 2>&1
  export BUN_PATH="$HOME/.bun/bin"
  export PATH="$BUN_PATH:$PATH"
  echo 'export PATH="$HOME/.bun/bin:$PATH"' >> ~/.bashrc
fi
ok "Bun $(bun --version) ready"

# ═══════════════════════════════════════════════════
# 4. CLONE REPOSITORY
# ═══════════════════════════════════════════════════
info "[4/8] Cloning repository..."
rm -rf "$INSTALL_DIR"
git clone --depth=1 "$REPO_URL" "$INSTALL_DIR" 2>/dev/null || {
  # Repo might be private — try with token
  if [ -n "$GITHUB_TOKEN" ]; then
    git clone --depth=1 "https://brendadeeznuts1111:$GITHUB_TOKEN@github.com/brendadeeznuts1111/sportsterminal.git" "$INSTALL_DIR"
  else
    fail "Could not clone. If repo is private, set GITHUB_TOKEN env var and retry."
  fi
}
cd "$INSTALL_DIR"
git checkout main 2>/dev/null || true
ok "Repository cloned to $INSTALL_DIR"

# ═══════════════════════════════════════════════════
# 5. DATABASE MIGRATION FIX
# ═══════════════════════════════════════════════════
info "[5/8] Fixing database migration for fresh installs..."
cd "$INSTALL_DIR/backend"
bun install >/dev/null 2>&1
mkdir -p data
  if bun run scripts/migrate.ts 2>&1; then
    ok "Database initialized"
  else
    fail "Migration failed — check error above"
  fi

# ═══════════════════════════════════════════════════
# 6. ENVIRONMENT CONFIGURATION
# ═══════════════════════════════════════════════════
info "[6/8] Configuring environment..."

JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
TUNNEL_TOKEN="${TUNNEL_TOKEN:-}"

cat > "$INSTALL_DIR/deploy/.env" << EOF
# Generated by auto-setup on $(date -u +%Y-%m-%d)
JWT_SECRET=$JWT_SECRET
TUNNEL_TOKEN=$TUNNEL_TOKEN
EOF

ok "Environment configured"

# ═══════════════════════════════════════════════════
# 7. BUILD AND START
# ═══════════════════════════════════════════════════
info "[7/8] Building and starting containers..."
cd "$INSTALL_DIR/deploy"
docker compose build app >/dev/null 2>&1
docker compose up -d app >/dev/null 2>&1

info "  Waiting for health check..."
for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
  sleep 3
  if curl -sf http://localhost:3000/health >/dev/null 2>&1; then
    ok "Health check passed"
    break
  fi
  if [ "$i" = 12 ]; then
    warn "Health check timeout — check logs: docker compose logs app"
  fi
done

# ═══════════════════════════════════════════════════
# 8. SSH KEY GENERATION + GITHUB SETUP
# ═══════════════════════════════════════════════════
info "[8/8] Generating SSH deploy key..."
if [ ! -f ~/.ssh/id_ed25519 ]; then
  ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519 -C "deploy@$DOMAIN" >/dev/null 2>&1
fi

PUBLIC_KEY=$(cat ~/.ssh/id_ed25519.pub)

# Register deploy key via GitHub API (if GITHUB_TOKEN provided)
if [ -n "$GITHUB_TOKEN" ]; then
  RESP=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST "https://api.github.com/repos/brendadeeznuts1111/sportsterminal/keys" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "Content-Type: application/json" \
    -d "{\"title\":\"VPS Deploy Key ($DOMAIN)\",\"key\":\"$PUBLIC_KEY\",\"read_only\":false}" 2>/dev/null)
  if [ "$RESP" = "201" ]; then
    ok "GitHub deploy key registered"
  else
    warn "Could not register deploy key (HTTP $RESP) — add manually"
  fi
fi

# Register GitHub Actions secret (if GITHUB_TOKEN provided)
if [ -n "$GITHUB_TOKEN" ] && command -v gh &>/dev/null; then
  gh secret set VPS_SSH_KEY --repo "brendadeeznuts1111/sportsterminal" --body "$(cat ~/.ssh/id_ed25519)" 2>/dev/null && \
    ok "GitHub Actions secret VPS_SSH_KEY set" || true
fi

# ═══════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  ✅ SETUP COMPLETE${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  ${CYAN}Server:${NC}     http://localhost:3000/health"
echo -e "  ${CYAN}Domain:${NC}      https://$DOMAIN"
echo -e "  ${CYAN}Project:${NC}     $INSTALL_DIR"
echo ""

if [ -z "$TUNNEL_TOKEN" ]; then
  echo -e "  ${YELLOW}⚠️  Cloudflare Tunnel not configured${NC}"
  echo ""
  echo "  To enable HTTPS access:"
  echo "  1. Go to https://dash.cloudflare.com → Zero Trust → Networks → Tunnels"
  echo "  2. Create a tunnel → Copy the token"
  echo "  3. nano $INSTALL_DIR/deploy/.env"
  echo "  4. Set: TUNNEL_TOKEN=your_token_here"
  echo "  5. cd $INSTALL_DIR/deploy && docker compose up -d tunnel"
  echo "  6. Route $DOMAIN → localhost:3000"
  echo ""
fi

if [ -n "$TUNNEL_TOKEN" ]; then
  info "Starting Cloudflare Tunnel..."
  cd "$INSTALL_DIR/deploy"
  docker compose up -d tunnel >/dev/null 2>&1
  ok "Tunnel started"
fi

if [ -z "$GITHUB_TOKEN" ]; then
  echo -e "  ${YELLOW}⚠️  Auto-deploy not configured${NC}"
  echo ""
  echo "  To enable auto-deploy on git push:"
  echo "  1. SSH public key:"
  echo "     ${CYAN}$PUBLIC_KEY${NC}"
  echo ""
  echo "  2. Add to GitHub:"
  echo "     Settings → Deploy keys → Add → Paste above"
  echo ""
  echo "  3. Add VPS_SSH_KEY secret:"
  echo "     Run: cat ~/.ssh/id_ed25519"
  echo "     GitHub → Settings → Secrets → Actions → Add"
  echo ""
fi

echo -e "  ${GREEN}Server is live at http://localhost:3000${NC}"
echo -e "  ${GREEN}Health: curl http://localhost:3000/health${NC}"
echo ""
